- climlab/dynamics/__init__.py
- climlab/dynamics/budyko_transport.py
- climlab/model/ebm.py
- climlab/process/time_dependent_process.py
- climlab/radiation/AplusBT.py
- climlab/radiation/Boltzmann.py
- climlab/radiation/__init__.py
Dear Brian,
I made a few modifications to the current release 0.2.11. I did not check them for compatibility with the newapi.
Here are the modifications listed:
- integrate_converge() for TimeDependentProcess class
- function call EBM() extended: T_init
new modules added (all for EBMs):
- AplusBT_CO2 - radiation 
- Boltzmann - blackbody radiation
- budyko_transport 
Hope this is helpful.
Regards Moritz
> Changes moritz

- docs/environment.yml
- docs/source/conf.py
- readthedocs.yml
added:
- readthedocs.yml
- environment.yml
updated the conf.py:
- included readthedocs in the HTML output
- added numpydoc to extensions 
This is in reference to issue #17 .
> Readthedocs

- docs/environment.yml
Adds to PR #24 and #25 and is in reference to issue #17 .
> added pip to environment for RTD

- climlab/__init__.py
- climlab/convection/convadj.py
- climlab/process/implicit.py
- climlab/process/time_dependent_process.py
- conda-recipe/meta.yaml
- setup.py
Fixes https://github.com/brian-rose/climlab/issues/52 and increments version number to 0.6.0.dev11
> Fix tendency units for ConvectiveAdjustment

- climlab/__init__.py
- climlab/process/__init__.py
- climlab/process/external_forcing.py
- climlab/radiation/radiation.py
- climlab/tests/test_grey_radiation.py
- conda-recipe/meta.yaml
- setup.py
This introduces a new Process class
```
climlab.process.ExternalForcing
```
that allows the user to provide arbitrary additional tendencies for state variables.
Basically just implements the suggestion in #76 along with a bit of documentation and one test.
> Implement a new ExternalForcing class

- climlab/__init__.py
- climlab/radiation/water_vapor.py
- conda-recipe/meta.yaml
- setup.py
Closes https://github.com/brian-rose/climlab/issues/108
> Initialize ManabeWaterVapor properly

- climlab/__init__.py
- climlab/radiation/insolation.py
- climlab/tests/test_domain2D.py
- conda-recipe/meta.yaml
- setup.py
Quick fix for #121 
This fixes the broadcasting of the insolation array for 2D (lat,lon) domains.
> Implement 2D seasonal insolation for EBM

- climlab/solar/orbital/table.py
- climlab/tests/test_insolation.py
WIP to address #128 
I added a new test for smooth insolation at high interpolation frequency, currently failing.
> Fix insolation wiggles

- climlab/convection/akmaev_adjustment.py
- climlab/tests/test_rcm.py
> Fix multi-dimensional moist convective adjustment

- climlab/radiation/rrtm/rrtmg.py
- docs/README.rst
- docs/environment.yml
- docs/source/api/climlab.surface.turbulent.rst
- docs/source/api/climlab.utils.data_source.rst
- docs/source/conf.py
- docs/source/contributing.rst
- readthedocs.yml
> Use correct input argument for tauaer

- README.rst
- conda-recipe/meta.yaml
- docs/README.rst
- docs/source/_templates/layout.html
- docs/source/contact.rst
- docs/source/contributing.rst
- docs/source/installation.rst
- docs/source/tutorial.rst
- setup.py
> Update all references to source repo

- README.rst
- climlab/__init__.py
- conda-recipe/meta.yaml
- setup.py
Because I messed something up with the 0.8.0 release.
> Bump version to 0.8.1

- docs/source/installation.rst
Add instructions for installing on Google Colab following #175
> Updated installation docs including Colab

- climlab/radiation/rrtm/rrtmg.py
- climlab/tests/test_rrtm.py
This should fix climlab/main #74 and also fix climlab/main #172 .
Please let me know if you have any comments, feedback, or questions.
> Bugfixes for #74 and #172

- climlab/solar/insolation.py
> Remove debugging output

- README.rst
- setup.py
Bump the version number and add release notes
> Release candidate for version 0.8.2

- climlab/solar/insolation.py
Closes #192 
The zenith angle formulas were mislabeled in the inline comments, which led to a confusing factor of pi. This PR cleans up the internal code to clarify what zenith angles are being calculated, and also factors out the geometric formula for variations in Earth-Sun distance.
No change in any public-facing APIs and no change in the returned insolation values, so this shouldn't break anything.
> Refactor insolation code to clarify zenith angle formulas

- climlab/dynamics/advection_diffusion.py
This PR addresses an issue with the diagnostics produced by the `AdvectionDiffusion` family of processes. Some fields were declared as diagnostics but were not properly wrapped as Field objects, which meant that they failed to convert to Xarray objects when using `climlab.to_xarray()`
No changes in functionality, but improved diagnostics reporting.
This reduces the number of annoying warning messages generated during calls to `climlab.to_xarray()`.
> Make diffusive and advective fluxes proper Field objects

- climlab/process/energy_budget.py
- docs/environment.yml
- docs/source/conf.py
> Get inheritance graphs working again

- docs/source/api/climlab.radiation.CAM3.rst
- docs/source/architecture.rst
> Basic docs on additive diagnostics

- docs/source/quickstart.rst
> Update the quickstart doc page

- climlab/radiation/absorbed_shorwave.py
- climlab/tests/test_ebm.py
Closes #250 
Adding a new test here, expecting it to fail. Then I'll do the fix.
> Preserve ASR diagnostic array shape for simple EBM
