.coveragerc, .travis.yml, climlab/tests/test_grey_radiation.py, climlab/tests/test_insolation.py
This adds some basic testing using the py.test framework, which I basically just copied from the Courseware notebooks. If you want to run the tests yourself, just type ``py.test -v`` (for verbose) in the project directory.
I also added support for continuous integration using [travis-ci](https://travis-ci.org/). Travis-ci (for "continuous integration") is a service that automatically builds the project and runs the tests every time a new commit or pull request is made. [Here is an example](https://travis-ci.org/rabernat/climlab/builds/109492019) of what travis-ci does on my climlab fork. If your testing is comprehensive, you can merge new pull requests with confidence after seeing that they don't break your tests. This makes it much easier for outsiders to contribute to the project. All …
=> add minimal tests and travis-ci integration

README.rst
This adds those pretty badges to the README.rst file which link to the pypi package, the travis-ci build, and the codecov coverage report. This will give the package instant open source cred! ;)
=> added badges to readme

.travis.yml
This should allow the test environment to build the CAM3Radiation module.
=> add `gcc` to the list of conda packages

climlab/process/process.py
Warning message added in a place of a KeyError if a subprocess, not in the subprocess dictionary, is removed. Verbose option was added, with a default: Verbose = True.  
The actual message is a suggestion; I wanted to keep it short, but it may be useful to explicitly tell the user that the subprocess is not in the subprocess dictionary instead of the current message:
> WARNING: Subprocess does not exist
These changes do not seem to conflict with any of the documentation on remove_subprocess, but additional writing about the verbose option could be introduced.
This is in reference to issue #21 .
=> process.remove_subprocess warning

docs/environment.yml
added nbsphinx to the dependencies in environment.yml so that the extension nbspinx can be imported 
This adds to PR #24 and is in reference to issue #17 .
=> fix Readthedocs

climlab/process/process.py, climlab/tests/test_ebm.py
Conversion method was added to process.py from dtype(int) to dtype(float) when setting a state variable.  Without the conversion a TypeError is raised when setting the state variable using 2 different methods...this conversion needed to be added in the 2 areas where the state variable is set.  
Also added is a test in test_ebm.py, which creates 2 models and sets the state variable 2 different ways with integers (the test passed locally). 
This is in references to issue #29 .
=> Int to float conversion and test

climlab/domain/domain.py, climlab/domain/initial.py, climlab/tests/test_domain2D.py
surface_2D creates the 2D domain and surface_state_2D sets up the state variable dictionary
-  in domain.py I added lon earlier in the code to ensure that lon is the 2nd dimension
- in initial.py the initial Ts is initialized with the 2nd legendre polynomial at each longitude 
- documentation and examples are included 
as of now, the budyko transport cannot step forward with the 2D state, but I will create an issue and  submit a pull request of the change needed after this is merged
=> 2D domain and surface state

climlab/domain/field.py, climlab/radiation/insolation.py, climlab/tests/test_domain2D.py
to_latlon was added to field.py and is used in 2 spots in insolation.py
- P2 insolation and annual mean insolation are now computed for 1D and 2D domains using np.meshgrid
- the axis that the array is broadcasted on is longitude, but this can be set to latitude if the array is longitude dependent 
A test for the creation of non-zero insolation arrays with 2D domains was also included
This is in reference to issue #34
=> Insolation for a 2D domain

climlab/model/ebm.py, climlab/process/time_dependent_process.py, climlab/tests/test_ebm.py
The problem when integrating forward was the 'icelat' diagnostic having the datatype NoneType.  I added code that removes the 'icelat' diagnostic if 'iceline' is not a subprocess of the albedo subprocess.  Ideally, the diagnostic would remain and would return None if model.icelat is called, but I couldn't find a way to do this.  I also initialized the 'icelat' diagnostic again if the user changes back to an albedo subprocess that needs the diagnostic.
I have also included a test that changes the albedo and integrates forward, then asserts that the 'icelat' returned is expected.  
This is in reference to issue #36  .
=> Integrate an EBM forward after changing the albedo

climlab/radiation/_cam3_interface.py
The build procedure for the `CAM3Radiation` module now checks to see if we're on OSX (darwin) and if so, uses `install_name_tool` to fix linker problems on the .so compiled object.
This fixes issue #40.
=> Fix @rpath problem on OSX so we can use conda-installed gcc compilers

climlab/__init__.py, climlab/process/time_dependent_process.py, conda-recipe/meta.yaml, setup.py
Some changes to how tendencies are computed and stored.
Now when the `compute()` method is called for any subprocess (which occurs for every timestep), the `tendencies` dictionary of every subprocess is updated with the sum of all its subprocess tendencies.
This doesn't change the model behavior but leaves more useful diagnostic information in all the `tendencies` dictionaries.
=> Always add up subprocess tendencies

courseware/Introducing the Column Model.ipynb, courseware/Two_layer_atmosphere.ipynb, paper.bib
In connection with the review in https://github.com/openjournals/joss-reviews/issues/659, this PR fixes the references for the JOSS paper by adding DOIs. Additonally, two examples have been ported from Python 2.7 to Python 3, since the [docs](http://climlab.readthedocs.io/en/latest/installation.html#required) claim, that climlab is made for this version.
=> Fix references and examples

climlab/__init__.py, climlab/dynamics/__init__.py, climlab/dynamics/diffusion.py, climlab/model/ebm.py, climlab/process/implicit.py, climlab/process/process.py, climlab/process/time_dependent_process.py, climlab/radiation/absorbed_shorwave.py, climlab/surface/albedo.py, climlab/tests/test_cam3rad.py, climlab/tests/test_domain2D.py, climlab/tests/test_ebm.py, climlab/tests/test_emanuel_convection.py, climlab/tests/test_grey_radiation.py, climlab/tests/test_insolation.py, climlab/tests/test_rcm.py, climlab/tests/test_rrtm.py, conda-recipe/meta.yaml, docs/source/contributing.rst, setup.py
Lots of internal reorganization to modernize the EBM implementation and add a moist diffusion process:
- `climlab.dynamics.Diffusion` and its subclasses are improved:
- automatically computes flux and flux convergence diagnostics
- The diffusivity `K` can be freely adjusted by the user; the diffusivity matrix is automatically recomputed.
- New subclass `MeridionalHeatDiffusion` is tailor-made for dry EBMs and automatically computes flux diagnostics in the appropriate units (PW and W/m2)
- A brand new class for diffusion on moist static energy gradients (moist EBM): `climlab.dynamics.MeridionalMoistDiffusion`
- `climlab.EBM()` and its daughter classes are significantly reorganized to better respect CLIMLAB principles:
- Essentially all the computations are done by subprocesses
- SW …
=> New and improved EBMs including moist option!

climlab/__init__.py, climlab/radiation/radiation.py, climlab/tests/test_rrtm.py, conda-recipe/meta.yaml, setup.py
This implements a new option to set 
```
ozone_file=None
```
as input to radiation processes, e.g. RRTMG.
This flag, in conjunction with ```absorber_vmr=None``` will initialize the process with zero ozone.
This fixes #70, allowing the user to set whatever ozone values they want after creating the process object.
=> Implement ozone_file=None option

climlab/__init__.py, climlab/radiation/rrtm/rrtmg_lw.py, climlab/radiation/rrtm/rrtmg_sw.py, climlab/radiation/rrtm/utils.py, climlab/tests/test_rrtm.py, conda-recipe/meta.yaml, setup.py
This should close #90 and #89. The workaround suggested in #90 will no longer be needed.
Add a simple test for an RRTMG process with insolation specified on a latitude grid for a specific day of the year.
Make the conversion routine `_climlab_to_rrtm_sfc` more robust to broadcasting errors.
Before merging this, it would be good to add an example to the docs.
=> Fix broadcasting error for fixed insolation

climlab/__init__.py, climlab/radiation/radiation.py, climlab/tests/test_rrtm.py, conda-recipe/meta.yaml, setup.py
This should close #95 
When initializing Radiation objects, the ozone interpolation now checks to see if there are any NaNs caused by grid points beyond the bound of the ozone file. 
If NaNs are found, a warning is issued and the interpolation is redone using scipy's option to extrapolate to out-of-bounds values.
A test of CAM3 and RRTMG processes on large 2D grids is added.
=> Fix interpolation

pyproject.toml, setup.py
Adding dependencies to setup.py and adding an error message if numpy is not already installed, as it's used before the install_requires can trigger. This isn't really optimal, but I'm not 100% sure how this issue would be solved properly. With a requirements file maybe?
=> dependencies in setup.py

climlab/utils/data_source.py
For #116, I added a timeout in the `request.get`. 
Adds a 5 minute timeout error for the download of remote files. For more information regarding `requests.get`, see here: https://requests.readthedocs.io/en/latest/user/quickstart/#timeouts
=> Adds timeout to download

climlab/radiation/radiation.py
For an `xr.DataArray()` with 1-dimensional coordinates, `da.interp_like()` actually calls scipy's [interp1d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html) function, rather than [interpn](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interpn.html). As a result, to extrapolate to values outside the domain, you need to pass `fill_value='extrapolate'`, rather than `fill_value=None`.
=> Changing fill_value from None to 'extrapolate' for ozone data

.github/workflows/build-and-test.yml, README.rst, ci/requirements-linux.yml, ci/requirements-macos.yml, ci/requirements-windows.yml, climlab/__init__.py, climlab/domain/initial.py, climlab/process/process.py, climlab/process/time_dependent_process.py, climlab/utils/attrdict/__init__.py, climlab/utils/attrdict/default.py, climlab/utils/attrdict/dictionary.py, climlab/utils/attrdict/mapping.py, climlab/utils/attrdict/merge.py, climlab/utils/attrdict/mixins.py, climlab/utils/attrdict/setup.py, conda-recipe/meta.yaml, docs/environment.yml, docs/source/installation.rst, setup.py
Remove attrdict package from dependencies (incompatible with Python 3.10)
Instead I've bundled the source code from [the archived attrdict project home](https://github.com/bcj/AttrDict) into `climlab.utils`, and changed the import paths for the `Mappings` abstract base class so that it continues to work under Python 3.10
Also switched on testing for Python 3.10 to the GitHub workflow matrix.
=> Python 3.10 compatibility

climlab/domain/field.py, climlab/radiation/__init__.py, climlab/radiation/greygas.py, climlab/radiation/transmissivity.py, docs/source/api/climlab.radiation.rst
This should fix #182 
Also cleaning up some documentation, and addressing a problem I just noticed:
The classes`climlab.radiation.greygas.GreyGas` and `climlab.radiation.greygas.GreyGasSW` don't appear in the [API documentation for the radiation module](https://climlab.readthedocs.io/en/latest/api/climlab.radiation.html).
=> Replace deprecated numpy code

.github/workflows/build-and-test.yml
Try to speed up the test builds by using mambaforge instead of conda
=> use mambaforge for CI builds

.github/workflows/build-and-test.yml, README.rst, docs/source/installation.rst
Does climlab build and test properly under Python 3.11?
=> Add Python 3.11 tests and drop Python 3.7

climlab/tests/test_domain2D.py
Add a new test suite for an EBM with longitude dimension and a diurnal cycle.
We are testing a few things:
- Can we create an EBM with an `InstantInsolation` process?
- does the zonal mean instantaneous insolation at model creation time equal the daily average insolation calculated at the same model time?
- Can we timestep the model forward for one day?
- Does the time- and zonal average insolation over a one-day integration equal the daily mean insolation centered 12 hours after model creation?
=> Test diurnal ebm

climlab/radiation/rrtm/rrtmg.py, climlab/radiation/rrtm/rrtmg_lw.py, climlab/radiation/rrtm/rrtmg_sw.py, climlab/radiation/rrtm/utils.py, climlab/tests/test_rrtm.py, setup.py
Working on fully supporting aerosols in the climlab interface for RRTMG radiation.
This PR (work in progress) will address #195 and #79. It will be possible to pass aerosol optical properties through to RRTMG_SW and RRTMG_LW with the correct dimensionality for both single column and 2D (usually latitude-pressure) grids.
Full support for 3D grids with RRTMG is still not there, as discussed in https://github.com/climlab/climlab/issues/86
=> Support for aerosols in RRTMG

climlab/tests/test_rcm.py
#203 reports a new issue with increasing the number of vertical levels in the radiative-convective model. This wasn't caught by our tests because we never increased the number of levels in those tests.
This PR will add a test that will fail until #204 is merged.
=> Add tests for larger number of levels in RCM

climlab/convection/akmaev_adjustment.py
Closes #200
Following [advice in the Numba docs](https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit), this PR explicitly sets `nopython=True` in the call to `numba.jit`.
There's no advantage to the old fall-back mode anyway. The jit call is wrapped in a `try...except` block already so if compilation fails for some reason, we fall back to pure python.
This makes some annoying deprecation notices go away.
=> Set nopython=True for Numba

climlab/process/process.py, climlab/tests/xarray_test.py
In this feature, when one calls model.to_xarray(timeave=True), the output would be the time-averaged diagnostics and not the instantaneous values. The default value for timeave is False, and in such a case the original functionality is kept unchanged.
=> adding support for time-averaging in xarray exporting of diagnostics

climlab/radiation/rrtm/rrtmg_sw.py, climlab/radiation/rrtm/utils.py
Climlab previously had a roll command over the optical tables of aerosols in SW. This was done to make the bands monotonically increasing, since that is not the case for the choice in rrtmg. However, this choice caused a bug when feeding a non-spectrally trivial table (which was painful to debug). So this line has been removed in this PR. Also, a flag was added to control flipping along the last axis (lev) to reverse the pressure order. The default is True, which is the same functionality as before, but now one can control it externally.
=> SW aerosol table roll bug fix

climlab/process/__init__.py, climlab/process/limiter.py, climlab/tests/test_ebm.py, docs/source/api/climlab.process.limiter.rst, docs/source/api/climlab.process.rst
This PR introduces a new process class `climlab.process.Limiter()` that implements flexible minimum / maximum values for state variables. 
This process can be added as a subprocess to any model to specific minimum and/or maximum allowable values for state variables. It is implemented as an `adjustment` type of process. At every timestep, the necessary adjustment to keep state variables within the allowable range is computed and applied. The adjustment (and also the corresponding tendency per unit time) are stored as internal process attributes just like every other Process, and so available for diagnostic use.
Some basic testing and basic documentation are included.
=> New Limiter process that implements min/max bounds for state variables

climlab/model/column.py, climlab/process/process.py, climlab/process/time_dependent_process.py, climlab/radiation/__init__.py, climlab/radiation/greygas.py, climlab/radiation/insolation.py, climlab/radiation/nband.py, climlab/surface/albedo.py, climlab/tests/test_grey_radiation.py
This PR addresses #202 
We will now assume that diagnostics produced by subprocesses that share a name are intended to be additive with each other. This assumes that they share the same unit, and the values are not tilmestep-dependent (e.g. they represent changes per unit time rather than time-integrated values).
Implementation requires some changes in the logic for how diagnostics are handled, which has been a bit of a mess.
=> Make same-named diagnostics additive

climlab/model/__init__.py, climlab/model/column.py, climlab/radiation/greygas.py
This PR further reduces warnings associated with attempts to convert `Field` variables into xarray format, addressing #220.
Along the way, I think this fixes an unreported bug in the diagnostics produced by `climlab.BandRCModel`. We need to sum over spectral bands to get valid diagnostics for things like ASR and OLR.
This PR also fixes an oversight in the namespace organization. Previously it was not possible to import things like
```
from climlab.model import EBM
```
That is now fixed. Related to #85
=> Diagnostics improvements for GreyGas model

.github/workflows/build-and-test.yml
Mambaforge is now [deprecated](https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/).
This PR switches the CI script to install Miniforge instead. Functionality should be identical but fewer warnings from GitHub Actions.
=> Switch CI builds to use Miniforge

.github/workflows/build-and-test.yml, .readthedocs.yaml, climlab/convection/__init__.py, climlab/convection/simplified_betts_miller.py, climlab/tests/test_sbm_convection.py, docs/environment.yml, docs/source/api/climlab.convection.SimplifiedBettsMiller.rst, docs/source/api/climlab.convection.rst, docs/source/conf.py, environment.yml
This PR adds a new process to climlab for the Simplified Betts Miller convection scheme (Frierson 2007).
The convection code itself and a basic Python wrapper are at https://github.com/climlab/climlab-sbm-convection/. This PR adds Python code for a climlab-native Process object `climlab.convection.SimplifiedBettsMiller` that can be coupled to radiation etc.
Still to do:
=> Add SimplifiedBettsMiller convection process

climlab/convection/emanuel_convection.py, climlab/convection/simplified_betts_miller.py, climlab/dynamics/__init__.py, climlab/dynamics/large_scale_condensation.py, climlab/tests/test_moist_model.py, docs/source/api/climlab.dynamics.LargeScaleCondensation.rst, docs/source/api/climlab.dynamics.rst, docs/source/conf.py
This PR adds a new process object that handles condensation associated with large-scale moisture convergence. This is necessary to prevent supersaturation from occurring in the presence of dynamics that advect or diffuse water vapor.
Still to do:
=> Add LargeScaleCondensation process

environment.yml
This will keep the tests passing on main branch until #235 is done and we're ready to fully support zenith angle averaging.
=> Temporary pin to previous climlab-rrtmg

climlab/radiation/cam3.py, environment.yml
Closes #238 
This PR also pins the build environment to previous version of climlab-cam3-radiation until #235 is merged.
=> Check to make sure CAM3 radiation gets scalar greenhouse gas VMRs

docs/environment.yml
This PR is an attempt to get the docs building again.
Builds on readthedocs are currently failing with
```
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/climlab/conda/241/lib/python3.12/site-packages/sphinx/events.py", line 404, in emit
results.append(listener.handler(self.app, *args))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/docs/checkouts/readthedocs.org/user_builds/climlab/conda/241/lib/python3.12/site-packages/nbsphinx/__init__.py", line 1714, in html_collect_pages
sphinx.util.console.brown, len(files)):
^^^^^^^^^^^^^^^^^^^
File "/home/docs/checkouts/readthedocs.org/user_builds/climlab/conda/241/lib/python3.12/site-packages/sphinx/util/__init__.py", line 157, in __getattr__
raise AttributeError(msg)
AttributeError: module 'sphinx.util' …
```
=> Pin to previous sphinx version due to nbsphinx incompatibility

climlab/radiation/insolation.py, climlab/tests/test_rrtm.py
This PR finished the abandoned work from #235 which was separated from #243. Trying to add full support for different time-averaging options for the cosine of the zenith angle.
=> Fully support and test coszen weighting options

.github/workflows/build-and-test.yml, README.rst, docs/source/installation.rst
This should fail until the Python 3.13 build for climlab-rrtmg is available on conda-forge (in progress).
=> Test on Python 3.13

climlab/radiation/rrtm/rrtmg.py, climlab/tests/test_rrtm.py
Closes #254 
First step is to add changes in parameter `S0` to the tests we are already doing for propagation of SW parameters for RRTMG processes. This should fail for now.
=> Fix propagation of solar constant parameter
